included:
  - iOSTemplate
  - iOSTemplateTests
excluded:
  - BuildTools/.build
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - array_init

identifier_name:
  excluded:
    - id
number_separator:
  minimum_length: 5
file_name:
  excluded:
    # - main.swift
    # - LinuxMain.swift
    # - TestHelpers.swift
    # - shim.swift
    # - AutomaticRuleTests.generated.swift